#!/bin/bash
#Runs drush-batcher as part of an automatic migration. Entrypoint to the k8s job
#Always runs updb --y and can optionally run partial or total cache clears
#eg: run-drush-migrations all / run-drush-migrations css-js

declare -r CLEAR_CACHES=$1
if [[ -z "$CLEAR_CACHES" ]] ; then
    COMMAND="drush updb --y"
else
    COMMAND="drush updb --y && drush cc $CLEAR_CACHES"
fi

drush-batcher -c "$COMMAND" 2>&1

# We always want to exit with a success code, as otherwise this can
# cause the pod and subsequently CI/CD pipeline to "fail" on errors
# we don't care about. Any errors we do care about will alert to PagerDuty.
exit 0
